### ISSUE TITLE
Why does aptitude update result in an error?

### ISSUE THREAD

**Issue by stefco** [stefco/geco_vm#26]
Apparently it canmt find some index files:

```
    virtualbox-iso: Ign http://software.ligo.org precise/contrib Translation-en_US
    virtualbox-iso: Ign http://software.ligo.org precise/contrib Translation-en
    virtualbox-iso: Fetched 62.3 kB in 3s (20.6 kB/s)
    virtualbox-iso: W: Failed to fetch http://software.ligo.org/lscsoft/debian/dists/wheezy/Release  Unable to find expected entry 'contrib/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
    virtualbox-iso:
    virtualbox-iso: E: Some index files failed to download. They have been ignored, or old ones used instead.
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 255

```

**Comment by stefco** [comment]
Again:

```
   virtualbox-iso: Ign http://toolkit.globus.org precise/contrib Translation-en
    virtualbox-iso: Ign http://software.ligo.org precise/contrib Translation-en_US
    virtualbox-iso: Ign http://software.ligo.org precise/contrib Translation-en
    virtualbox-iso: Fetched 62.3 kB in 3s (19.8 kB/s)
    virtualbox-iso: W: Failed to fetch http://software.ligo.org/lscsoft/debian/dists/wheezy/Release  Unable to find expected entry 'contrib/binary-i386/Packages' in Release file (Wrong sources.list entry or malformed file)
    virtualbox-iso:
    virtualbox-iso: E: Some index files failed to download. They have been ignored, or old ones used instead.
    virtualbox-iso: + true
    virtualbox-iso: + aptitude --no-gui -o Aptitude::Cmdline::ignore-trust-violations=true -y -q full-upgrade
    virtualbox-iso: Reading package lists...
    virtualbox-iso: Building dependency tree
```
